apiVersion: v1
kind: Secret
metadata:
  name: backend
type: Opaque
data:
  KAFKA_HOST: cGtjLTZvanYyLnVzLXdlc3Q0LmdjcC5jb25mbHVlbnQuY2xvdWQ6OTA5Mg==
  KAFKA_CLIENT_ID: YmFja2VuZA==
  KAFKA_SASL_USERNAME: TDVON1NKNDdYSFVBNE1JWg==
  KAFKA_SASL_PASSWORD: RVh6R2orZStsME5BK0hHRkpIUmdiUFJvdWNJYWRIZElWOFdHN3daZjhyRGFwSmY0ZkNxNll5UUNpa3pGZmd3bQ==
  KAFKA_USE_SSL: dHJ1ZQ==
  DB_CONNECTION: bXlzcWw=
  DB_USERNAME: cm9vdA==
  DB_PASSWORD: SFQ0SjNKTEt5MQ==
  DB_HOST: bXlzcWw=
  DB_DATABASE: YmFja2VuZA==
  DB_PORT: MzMwNg==
  

