apiVersion: v1
kind: Secret
metadata:
  name: gateway
type: Opaque
data:
  BOOTSTRAP_SERVERS: cGtjLTZvanYyLnVzLXdlc3Q0LmdjcC5jb25mbHVlbnQuY2xvdWQ6OTA5Mg==
  SECURITY_PROTOCOL: U0FTTF9TU0w=
  SASL_MECHANISMS: UExBSU4=
  SASL_USERNAME: TDVON1NKNDdYSFVBNE1JWg==
  SASL_PASSWORD: RVh6R2orZStsME5BK0hHRkpIUmdiUFJvdWNJYWRIZElWOFdHN3daZjhyRGFwSmY0ZkNxNll5UUNpa3pGZmd3bQ==
  MYSQL_USERNAME: cm9vdA==
  MYSQL_PASSWORD: SFQ0SjNKTEt5MQ==
  MYSQL_HOST: bXlzcWw=
  MYSQL_DATABASE: Z2F0ZXdheQ==

